# Read the documentation before extending the defaults:
# https://docs.searxng.org/admin/settings/

use_default_settings: true

search:
  formats:
    - html
    - json # ¡Obligatorio si usas Open WebUI u otras aplicaciones IA!


server:
  secret_key: "wAMH0R8rqm8gZrDuPoBZJA0uvjkljQ"
  image_proxy: false
